In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df=pd.read_csv('./insurance.csv')
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [5]:
df.shape

(1338, 7)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [7]:
df.isnull()

        age    sex    bmi  children  smoker  region  charges
0     False  False  False     False   False   False    False
1     False  False  False     False   False   False    False
2     False  False  False     False   False   False    False
3     False  False  False     False   False   False    False
4     False  False  False     False   False   False    False
...     ...    ...    ...       ...     ...     ...      ...
1333  False  False  False     False   False   False    False
1334  False  False  False     False   False   False    False
1335  False  False  False     False   False   False    False
1336  False  False  False     False   False   False    False
1337  False  False  False     False   False   False    False

[1338 rows x 7 columns]

In [8]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [9]:
df.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [10]:
from sklearn.preprocessing  import LabelEncoder
sex_le=LabelEncoder()
smoker_le=LabelEncoder()
region_le=LabelEncoder()

In [11]:
df['sex']=sex_le.fit_transform(df['sex'])
df['smoker']=smoker_le.fit_transform(df['smoker'])
df['region']=region_le.fit_transform(df['region'])
df

      age  sex     bmi  children  smoker  region      charges
0      19    0  27.900         0       1       3  16884.92400
1      18    1  33.770         1       0       2   1725.55230
2      28    1  33.000         3       0       2   4449.46200
3      33    1  22.705         0       0       1  21984.47061
4      32    1  28.880         0       0       1   3866.85520
...   ...  ...     ...       ...     ...     ...          ...
1333   50    1  30.970         3       0       1  10600.54830
1334   18    0  31.920         0       0       0   2205.98080
1335   18    0  36.850         0       0       2   1629.83350
1336   21    0  25.800         0       0       3   2007.94500
1337   61    0  29.070         0       1       1  29141.36030

[1338 rows x 7 columns]

In [12]:
X=df.drop(["charges"],axis="columns")
Y=df["charges"]

In [13]:
X

      age  sex     bmi  children  smoker  region
0      19    0  27.900         0       1       3
1      18    1  33.770         1       0       2
2      28    1  33.000         3       0       2
3      33    1  22.705         0       0       1
4      32    1  28.880         0       0       1
...   ...  ...     ...       ...     ...     ...
1333   50    1  30.970         3       0       1
1334   18    0  31.920         0       0       0
1335   18    0  36.850         0       0       2
1336   21    0  25.800         0       0       3
1337   61    0  29.070         0       1       1

[1338 rows x 6 columns]

In [14]:
Y

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...
1333    10600.54830
1334     2205.98080
1335     1629.83350
1336     2007.94500
1337    29141.36030
Name: charges, Length: 1338, dtype: float64

In [15]:
X.shape

(1338, 6)

In [16]:
Y.shape

(1338,)

In [17]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=2)

In [18]:
X_train

      age  sex     bmi  children  smoker  region
882    21    0  22.135         0       0       0
505    37    1  30.875         3       0       1
798    58    0  33.100         0       0       3
792    22    0  23.180         0       0       0
201    48    0  32.230         1       0       2
...   ...  ...     ...       ...     ...     ...
466    60    0  28.700         1       0       3
299    48    0  28.880         1       0       1
493    61    1  43.400         0       0       3
527    51    0  25.800         1       0       3
1192   58    0  32.395         1       0       0

[1070 rows x 6 columns]

In [19]:
Y_train

882      2585.85065
505      6796.86325
798     11848.14100
792      2731.91220
201      8871.15170
           ...
466     13224.69300
299      9249.49520
493     12574.04900
527      9861.02500
1192    13019.16105
Name: charges, Length: 1070, dtype: float64

In [20]:
X_test

      age  sex     bmi  children  smoker  region
17     23    1  23.845         0       0       0
1091   55    0  29.830         0       0       0
273    50    1  27.455         1       0       0
270    18    1  29.370         1       0       2
874    44    1  21.850         3       0       0
...   ...  ...     ...       ...     ...     ...
232    19    0  17.800         0       0       3
323    57    1  40.945         0       0       0
1337   61    0  29.070         0       1       1
1066   48    1  37.290         2       0       2
966    51    1  24.795         2       1       1

[268 rows x 6 columns]

In [21]:
Y_test

17       2395.17155
1091    11286.53870
273      9617.66245
270      1719.43630
874      8891.13950
           ...
232      1727.78500
323     11566.30055
1337    29141.36030
1066     8978.18510
966     23967.38305
Name: charges, Length: 268, dtype: float64

In [22]:
len(X_train)

1070

In [23]:
len(X_test)

268

In [24]:
len(Y_train)

1070

In [25]:
len(Y_test)

268

In [26]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression()
reg.fit(X_train,Y_train)

LinearRegression()

In [27]:
reg.predict(X_test)

array([ 1885.54165174, 11944.32273357, 10455.55488707,  2397.96696161,
        8271.55347048, 11234.41036809,  3376.43169724,  1072.63123623,
       12060.51395933,  9468.23322457, 11494.97066851,  5053.0305502 ,
       30093.5527384 ,  -228.58148206, 12784.84199754, 13402.21956446,
        4179.28948043,  7740.09899682, 29568.66245635,  2738.01455718,
       12343.38521075,  1881.51269934, 34087.95253065, 32103.24119851,
       30445.32061394,  8632.58788645,  2298.01995336, 15417.01187725,
        6168.10928884,  1942.95830544,  9636.84483913,  5642.81556233,
        4058.10854408,  4853.19902886,  9764.94270973,  4755.04190386,
       30007.20570516,  6403.4791383 , 27582.56773006, 14149.40158117,
         151.96770571, 28000.88252814,  7724.4555082 ,  1093.99727743,
       10434.24794603,  7636.92275042, 11467.16787872,  8328.38879353,
       10915.23415866, 13408.79328   ,  6150.60763788, -1131.05313916,
       26163.22877049, 36999.48645124,  6988.24506067, 17480.13399005,
        1018.83694558, 11202.85589973,  1775.35390886, 34195.62805741,
       11482.93499856,   489.95740987,  3859.74367758, 36051.47915417,
       -1428.73834052, 14328.37292632, 14447.33699801,  3547.73959496,
       13086.4043211 , 11047.27999843, 11195.05001964, 16319.16806083,
       10029.69471548,  9522.20376728, 15522.39790841, 12002.45799506,
        4004.69702408,  3510.12174794,  5490.17653227, 13128.9199443 ,
        8771.82281042, 12309.46045053,  9667.79765657, 27287.68697984,
       12790.05452343,  3828.26275901, 38670.29110584, 11019.60083986,
        8452.47984123, 11229.41055335, 11339.4032459 , 14744.9636076 ,
       11255.03748123, 13436.6866804 ,  5675.68835376, 25774.18377058,
        4802.47207367, 10695.16392711,  3083.49609515, 29128.1781461 ,
        6744.14121214,  3621.45701886,  2284.90090761, 16142.63905509,
        7743.99450366,  9909.25632884,  9809.85561134,  5217.94371569,
       15243.60845691, 34129.65579923,  3932.05307004, 11135.43095089,
       24974.58491491, 15196.34870014,  2109.56802097, 10238.04244103,
        8827.26636406,  6118.09284474, 11453.00870576, 28992.60115388,
        6185.07119212,  6796.38004975, 16007.47097303, 16618.20181147,
        8413.48368377, 26675.27315058, 35422.17964258, 11480.17024933,
        7928.5040558 ,  9505.55610531,  8313.45553744,  3299.55807657,
        2939.66896258,  4531.09220084,  8171.97567366,  8385.88030102,
        7196.89330173, 28798.69273278, 34783.89321682,  4004.80792333,
       27471.72298415,  4000.98272662,  6467.74992944, 13471.79662831,
        7640.81825725, 36599.60475814, 11632.338848  , 11176.81793909,
        8132.94575674,   139.36211328,  6128.3827736 ,  7343.67722403,
        4791.42565069, 11272.08677524, 11459.58372532, 15629.94726772,
        6221.72900476, 28022.48030541,  1817.25727984, 11850.04403479,
       17348.8574798 , 14093.51075429,  9135.77746229,  2643.67726663,
        4252.29103098,  9091.64865318, 19165.47389035, 28619.39904963,
       13039.98721697,  3108.76523149, 32669.04229311, 12723.2025417 ,
       33140.28344844, 34726.63313521, 11535.8676401 ,  7199.88544155,
        3024.22410514,  2738.01455718, 11807.82226082,  7517.80179646,
        2755.99762284,   996.35903981, 31500.42047313,  6981.97510029,
        5701.96925175, 27133.30941183,  6975.90000327,  2806.78733149,
        7756.08876538, 35216.05656821,  8145.26232535,  4480.71969408,
        9630.20617573, 27232.90944478,  6088.13270089, 40327.75571182,
       37083.16692232, 13381.78417846, 26961.74999462, 12285.99199376,
       37601.19299442,  7241.19040128,  4044.28958536,  1809.38543828,
       14457.64541495, 13847.63368951,  2545.43395147, 35826.12909961,
       12424.11686557,  8899.08300547,   747.97468776, 30768.7660853 ,
        3869.007392  ,  3833.5970121 , 12437.58188106, 14919.93398073,
       29278.44958711,  -475.84225118,  3336.07577736,  8301.60736115,
       40115.68844976,  8381.46393953, 35473.32544551, 27087.81718701,
       13568.80908294, 29028.31497875, 16893.22465803,  7775.19510378,
       15988.04055919,  7290.41681042, 10608.67726746,  3334.72630606,
        8423.76097226,  1750.4597282 , 32990.56624809, 31881.92819305,
       14441.70241637, 11037.05552582,  1382.84301454,  6137.49001937,
       10799.15221794,  4326.30554377, 10613.54039697,   661.59126724,
       34713.28762089, 32561.54987973, 10371.33933838, 26484.49202386,
       12661.21629752,  2113.0352194 , 10822.99887005,  2800.8592108 ,
        7898.64937714, 10288.02896912, 16725.91611812,  5619.38226062,
       10164.23107528,  -156.85099917, -1979.34595418,  1515.03753962,
       27904.40808058, 33822.00624667, 37719.74320731, -2054.82719361,
       16088.03494606, 36783.48306159, 13147.66223851, 33998.49281923])

In [28]:
reg.coef_

array([  251.36689613,   -35.4338166 ,   330.76133485,   589.05862101,
       23905.96516848,  -323.62760276])

In [29]:
reg.intercept_

np.float64(-11747.467172088811)

In [30]:
reg.score(X_test,Y_test)

0.7445422986536503

In [31]:
pred=reg.predict([[37,1,29.83,2,0,0]])
pred

C:\Users\Lakshman\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([8562.40202864])

In [32]:
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_score

cv = ShuffleSplit(n_splits=5, test_size=0.2, random_state=0)

cross_val_score(LinearRegression(), X, Y, cv=cv)

array([0.79987471, 0.74792712, 0.71092717, 0.77433601, 0.80803446])

In [33]:
from sklearn.model_selection import GridSearchCV

from sklearn.linear_model import Lasso
from sklearn.tree import DecisionTreeRegressor

def find_best_model_using_gridsearchcv(X,y):
    algos = {
        'linear_regression' : {
            'model': LinearRegression(),
            'params': {
                #'normalize': [True, False]
            }
        },
        'lasso': {
            'model': Lasso(),
            'params': {
                'alpha': [1,2],
                'selection': ['random', 'cyclic']
            }
        },
        'decision_tree': {
            'model': DecisionTreeRegressor(),
            'params': {
                'criterion' : ['mse','friedman_mse'],
                'splitter': ['best','random']
            }
        }
    }
    scores = []
    cv = ShuffleSplit(n_splits=5, test_size=0.2, random_state=0)
    for algo_name, config in algos.items():
        gs =  GridSearchCV(config['model'], config['params'], cv=cv, return_train_score=False)
        gs.fit(X,y)
        scores.append({
            'model': algo_name,
            'best_score': gs.best_score_,
            'best_params': gs.best_params_
        })

    return pd.DataFrame(scores,columns=['model','best_score','best_params'])

find_best_model_using_gridsearchcv(X,Y)

C:\Users\Lakshman\AppData\Roaming\Python\Python313\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning:
10 fits failed out of a total of 20.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Lakshman\AppData\Roaming\Python\Python313\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lakshman\AppData\Roaming\Python\Python313\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Lakshman\AppData\Roaming\Python\Python313\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Lakshman\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'squared_error', 'absolute_error', 'friedman_mse', 'poisson'}. Got 'mse' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\Lakshman\AppData\Roaming\Python\Python313\site-packages\sklearn\model_selection\_search.py:1135: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.72021502 0.74094898]
  warnings.warn(

,model,best_score,best_params
0,linear_regression,0.768220,{}
1,lasso,0.768218,"{'alpha': 1, 'selection': 'cyclic'}"
2,decision_tree,0.740949,"{'criterion': 'friedman_mse', 'splitter': 'ran..."

In [36]:
import pickle
with open('insurance.pickle','wb') as f:
    pickle.dump(reg,f)

In [37]:
import json
columns = {
    'data_columns' : [col.lower() for col in X.columns]
}
with open("columns.json","w") as f:
    f.write(json.dumps(columns))

In [34]:
import numpy as np

def predict_insurance_charges(age, sex, bmi, children, smoker, region):
    # 1. Transform categorical strings to labels using your trained encoders
    # Assuming le_sex, le_smoker, and le_region were saved from your training
    sex_encoded = sex_le.transform([sex])[0]
    smoker_encoded = smoker_le.transform([smoker])[0]
    region_encoded = region_le.transform([region])[0]
    
    # 2. Arrange features in the EXACT order used during model.fit()
    # Typical order: [age, sex, bmi, children, smoker, region]
    features = np.array([[age, sex_encoded, bmi, children, smoker_encoded, region_encoded]])
    
    # 3. Predict
    #prediction = model.predict(features)
    
    print(age," ",bmi," ",children," ",sex_encoded," ",smoker_encoded," ",region_encoded)
predict_insurance_charges(27,"male",23.4,2,"yes","southeast")

27   23.4   2   1   1   2

In [35]:
import joblib
# Save the model and encoders

joblib.dump(sex_le, 'sex_le.pkl')
joblib.dump(smoker_le, 'smoker_le.pkl')
joblib.dump(region_le, 'region_le.pkl')

['region_le.pkl']